groups:
- name: apache
  rules:

  # Alert for any instance that is unreachable for >1 minutes.
  - alert: Apache InstanceDown
    expr: apache_up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."
